name: Eleventy Build
on:
  pull_request:
    branches: [ main ]
    types:
      - closed
  push:
    branches: [ main ]

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build
        uses: cjerrington/actions-eleventy@master
        with:
          cname: static.quest
          install_dependencies: true
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: _site 
          publish_branch: gh-pages
          github_token: ${{ secrets.DEPLOY_TOKEN }}
